version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - flask-network
    depends_on:
      - db
  
  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  db_data:
